name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: yarn install -immutable
      - name: Run linter
        run: yarn lint
      - name: Build
        run: yarn build
      - uses: tj-actions/verify-changed-files@v9
        id: verify-changed-files
        with:
          files: |
            snap.manifest.json
      - name: Check if snap manifest updated
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Snap manifest not updated: ${{ steps.verify-changed-files.outputs.changed_files }}"
          exit 1
