name: Pull request

on:
  pull_request:
    branches: [master, dev]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: yarn install
      - run: yarn build
